-- Migration 002: summary_month, ai_summary, parent_property_id, municipal_valuation
-- Run against the live Supabase project via the SQL editor or psql.
--
-- What this adds:
--   bills.summary_month         DATE   — canonical billing period (first day of month).
--                                         For City of Cape Town this is the "Account Summary Month"
--                                         field on the bill. Used as the primary filter everywhere.
--   bills.ai_summary            JSONB  — array of insight bullet-point strings generated by Claude
--                                         during extraction (e.g. anomalous billing periods,
--                                         estimate reversals, meter reading offsets).
--   properties.parent_property_id UUID — self-reference. Unit records point at their parent
--                                         complex/erf record. Top-level properties have null here.
--   properties.municipal_valuation NUMERIC — latest known rateable valuation for this property
--                                         (taken from the base_value of the rates line item on
--                                         the most recent bill). Updated on every bill save.

-- ── bills ──────────────────────────────────────────────────────────────────────

alter table bills
  add column if not exists summary_month date,
  add column if not exists ai_summary jsonb;

-- Index for the period selector on the dashboard and bills list.
create index if not exists idx_bills_summary_month on bills(summary_month);

-- ── properties ────────────────────────────────────────────────────────────────

alter table properties
  add column if not exists parent_property_id uuid references properties(id) on delete set null,
  add column if not exists municipal_valuation numeric(14,2);

create index if not exists idx_properties_parent on properties(parent_property_id);
